# Generated by Django 4.2.7 on 2023-11-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_musicbrainz_connector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                ("id", models.IntegerField(db_column="id", primary_key=True, serialize=False, verbose_name="ID")),
                ("gid", models.UUIDField(db_column="gid")),
                ("name", models.CharField(db_column="name", max_length=255)),
                (
                    "edits_pending",
                    models.PositiveIntegerField(db_column="edits_pending", default=0, verbose_name="Edits Pending"),
                ),
                ("last_updated", models.DateTimeField(db_column="last_updated", verbose_name="Last Updated")),
            ],
            options={
                "verbose_name_plural": "Works",
                "db_table": "work",
                "managed": False,
            },
        ),
    ]
