# Generated by Django 5.0 on 2024-01-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_musicbrainz_connector", "0003_artistcredit_link_linktype_recording_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                ("id", models.IntegerField(db_column="id", primary_key=True, serialize=False, verbose_name="ID")),
                ("iso_code", models.CharField(db_column="iso_code", max_length=4, verbose_name="ISO Code")),
                ("iso_number", models.CharField(db_column="iso_number", max_length=3, verbose_name="ISO Number")),
                ("name", models.CharField(db_column="name", max_length=100, verbose_name="Name")),
                ("frequency", models.SmallIntegerField(db_column="frequency", default=0, verbose_name="Frequency")),
            ],
            options={
                "verbose_name_plural": "Scripts",
                "db_table": "script",
                "managed": False,
            },
        ),
    ]
