# Generated by Django 5.0 on 2024-01-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_musicbrainz_connector", "0005_language_alter_script_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleasePackaging",
            fields=[
                ("id", models.IntegerField(db_column="id", primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_column="name", max_length=255, verbose_name="Name")),
                ("child_order", models.IntegerField(db_column="child_order", verbose_name="Child Order")),
                ("description", models.TextField(db_column="description", verbose_name="Description")),
                ("gid", models.UUIDField(db_column="gid")),
            ],
            options={
                "verbose_name_plural": "Release Packaging",
                "db_table": "release_packaging",
                "ordering": ["name"],
                "managed": False,
            },
        ),
    ]
