# Generated by Django 5.0 on 2024-01-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_musicbrainz_connector", "0006_releasepackaging"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseStatus",
            fields=[
                ("id", models.IntegerField(db_column="id", primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_column="name", max_length=255)),
                ("child_order", models.IntegerField(db_column="child_order", verbose_name="Child Order")),
                ("description", models.TextField(db_column="description")),
                ("gid", models.UUIDField(db_column="gid")),
            ],
            options={
                "verbose_name_plural": "Release Statuses",
                "db_table": "release_status",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="worktype",
            options={"managed": False, "ordering": ["name"], "verbose_name_plural": "Work Types"},
        ),
    ]
