# Generated by Django 5.0 on 2024-01-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_musicbrainz_connector", "0007_releasestatus_alter_worktype_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseGroup",
            fields=[
                ("id", models.IntegerField(db_column="id", primary_key=True, serialize=False, verbose_name="ID")),
                ("gid", models.UUIDField(db_column="gid", verbose_name="GID")),
                ("name", models.CharField(db_column="name", max_length=2048)),
                ("comment", models.CharField(db_column="comment", default="", max_length=255, verbose_name="Comment")),
                (
                    "edits_pending",
                    models.PositiveIntegerField(db_column="edits_pending", default=0, verbose_name="Edits Pending"),
                ),
                ("last_updated", models.DateTimeField(db_column="last_updated", verbose_name="Last Updated")),
            ],
            options={
                "verbose_name_plural": "Release Groups",
                "db_table": "release_group",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReleaseGroupPrimaryType",
            fields=[
                ("id", models.IntegerField(db_column="id", primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_column="name", max_length=255)),
                ("child_order", models.IntegerField(db_column="child_order", verbose_name="Child Order")),
                ("description", models.TextField(db_column="description")),
                ("gid", models.UUIDField(db_column="gid", verbose_name="GID")),
            ],
            options={
                "verbose_name_plural": "Release Group Primary Types",
                "db_table": "release_group_primary_type",
                "ordering": ["name"],
                "managed": False,
            },
        ),
    ]
